name: Website Build
on:
  push:
    branches:
      - 'main'
    paths:
      - "documentation/**/*"
permissions:
  contents: read
  pages: write
  id-token: write
jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        ref: "develop/3.0"
        token: ${{ secrets.PUSHABLE_GITHUB_TOKEN }}
    - run: |
        git submodule update --init --recommend-shallow eng/submodules/silk.net-2.x
        cd eng/submodules/silk.net-2.x
        git fetch origin main
        git checkout FETCH_HEAD
        cd ../../..
        git add eng/submodules/silk.net-2.x
        git commit -m "Update Silk.NET 2.X submodule for website"
        git push
